"""Textos de ayuda de la interfaz.

Se mantienen fuera de streamlit_app.py por dos motivos: la interfaz queda legible, y las
explicaciones largas dejan de repetirse junto a cada control. En pantalla solo va una línea
breve; el desarrollo completo vive aquí y se consulta desde Ayuda.

Estructura: SECCIONES = {sección: [(titulo, cuerpo markdown), ...]}
"""

# Frases cortas que acompanan a un control concreto. La explicacion larga esta en SECCIONES.
BREVE = {
    "confianza": "How much to trust the result, not how good it is. Detail in Help › Results.",
    "efectividad": "Percentage relative to the site's reference ligand. Detail in Help › Results.",
    "pki": "−log₁₀ Ki: numeric and sortable. Detail in Help › Results.",
    "le": "Affinity per heavy atom. Detail in Help › Results.",
    "pose": "Every value in the row comes from this same pose.",
    "cavidades": "Real extent vs. search box. Detail in Help › Run.",
    "peptidos": "Rules and descriptors in Help › Ligands.",
    "gnina": "Independent second score. Detail in Help › Run.",
}

SECCIONES = {
    "Getting started": [
        ("What PoliScreen does",
         "It chains the full screening cycle: prepare the target, obtain compounds, dock them and "
         "evaluate binding quality.\n\n"
         "The difference from an ordinary docking panel is how it scores. Instead of rewarding "
         "affinity and contact count, it measures **which contacts** are made and **with which "
         "residues**, and adds a measure of **how much to trust** each result."),
        ("The order of work",
         "1. **Receptors** — download or upload the structure, choose what to keep and extract the "
         "co-crystallized ligand as the control.\n"
         "2. **Ligands** — build the series by reaction, generate peptides or upload ready structures.\n"
         "3. **Run** — define where to search and launch docking.\n"
         "4. **Results** — adjust the weighting and examine the ranking.\n\n"
         "The right-hand panel always shows what corresponds to the active step."),
        ("Save and restore your work",
         "**File › Save session** packs the analysis into a `.poliscreen` file. Restoring it brings "
         "back the tables, receptors and ligands, and lets you **change the weighting without "
         "repeating the docking**.\n\n"
         "The light session is a few megabytes; the full one adds poses and complexes."),
        ("The project folder",
         "Everything is written there: poses, complexes, PLIP XML and tables. Changing folder changes "
         "analysis, and anything already prepared in it (receptors, controls, ligands) is auto-detected "
         "on entry.\n\n"
         "PoliScreen runs inside Linux, so the path is a Linux path (`/home/user/...`). If you paste a "
         "Windows one —`\\\\wsl.localhost\\...`, `C:\\...` or the `home\\user\\...` fragment the Explorer "
         "copies— it is translated automatically and you are told which one was used."),
        ("What is worth downloading",
         "**File › Download results** builds a single ZIP with what you select, leaving no copies in the "
         "project folder.\n\n"
         "Almost everything there **already lives in that folder**: downloading only makes sense to move "
         "the analysis to another machine, attach it to a manuscript or archive it. That is why the items "
         "forming that minimal package are marked as **recommended**:\n\n"
         "- The **Methods** section, the only one that does not exist until you export it.\n"
         "- The **ranking**, the **interaction matrix** and the **ligand table**, which are the result "
         "and its traceability.\n"
         "- The **redocking validation**, the first thing a reviewer checks.\n"
         "- **Input receptors and ligands**, so someone else can repeat the run.\n\n"
         "The rest —poses, fused complexes, summary and energies of every pose— is regenerated by "
         "running again, and can take hundreds of megabytes."),
    ],
    "Receptors": [
        ("What preparation does",
         "Removes waters, adds hydrogens and keeps the original residue numbering.\n\n"
         "Keeping the numbering matters: if it changes, an active-site residue can end up identified with "
         "another's name and the whole pharmacophoric analysis is wrong."),
        ("Cofactors: when to keep them",
         "A cofactor that is part of the site (NADP in a reductase, for example) must be kept: the ligand "
         "competes or cooperates with it, and removing it changes the pocket shape.\n\n"
         "Ions and crystallization molecules that do not participate can be removed."),
        ("The co-crystallized control",
         "The most important piece of the setup. It defines the reference everything is measured against, "
         "marks the real binding site and enables protocol validation by redocking.\n\n"
         "When extracting it, provide its **SMILES**: the PDB format does not store bond orders and, "
         "without that template, heterocycles such as the benzofuroxan N-oxide are read incorrectly."),
        ("Why waters are removed",
         "Standard practice in rigid docking. AutoDock Vina does not model explicit waters or the cost of "
         "displacing them, so leaving them produces artifacts: they block the site or generate contacts "
         "that are not real.\n\n"
         "The exception is **conserved structural waters** that mediate binding in some systems. Keeping "
         "them is a case-by-case decision that must be justified; if you do, PoliScreen detects "
         "water-mediated bridges automatically."),
    ],
    "Ligands": [
        ("The three routes",
         "**Build by reaction** — start from a core and a reagent library, and filter by real chemical "
         "feasibility. What is docked is what can be synthesized.\n\n"
         "**Generate peptides** — enumerate sequences under composition and property rules.\n\n"
         "**Upload ready ligands** — already prepared structures. Their chemistry is read so ADMET and "
         "descriptors can be computed."),
        ("Peptides: the rules",
         "The alphabet is restricted by class (hydrophobic, cationic, aromatic…); a prefix or a suffix can "
         "be fixed, repeats forbidden or consecutive residues limited.\n\n"
         "The physicochemical filters discriminate most in antimicrobial peptides: **net positive charge** "
         "(the bacterial membrane is anionic) and moderate hydrophobicity."),
        ("Peptides: the descriptors",
         "**Net charge** at pH 7.4 — the trait most associated with antimicrobial activity.\n\n"
         "**GRAVY** — mean hydropathy; positive indicates overall hydrophobic character.\n\n"
         "**Hydrophobic moment** — amphipathicity: whether, folded into a helix, the hydrophobic residues "
         "sit on one face and the polar ones on the other. This is what enables membrane insertion.\n\n"
         "**Boman index** — tendency to bind other proteins; above 2.5 kcal/mol it is considered "
         "promiscuous."),
        ("Peptides: the termini",
         "**C-terminal amidation** removes the terminal negative charge and adds +1 to the net charge, "
         "which usually increases antimicrobial activity.\n\n"
         "**N-terminal acetylation** protects against aminopeptidases.\n\n"
         "**Head-to-tail cyclization** rigidifies the peptide: far fewer degrees of freedom, protease "
         "resistance and more reliable docking."),
        ("Peptides: the docking engine",
         "Vina treats the ligand as an independent torsion tree, and with the many rotatable bonds of a "
         "peptide the sampling stops covering the space (measured on saFtsZ, 23 Å box, exhaustiveness 8, "
         "one thread):\n\n"
         "| Residues | Rotatable bonds | Vina time |\n|---|---|---|\n"
         "| 3 | 15 | ~98 s |\n| 5 | 23 | > 2 min |\n| 10 | 43 | does not finish |\n\n"
         "That is why PoliScreen routes peptides of **5 to 20 residues automatically to AutoDock CrankPep "
         "(ADCP)**, which builds the conformation with a rotamer library instead of a torsion tree; below "
         "5 residues, or if ADCP is not installed, they fall back to Vina with a warning. Peptide docking "
         "still ranks candidates rather than asserting an exact binding mode, but ADCP handles their "
         "flexibility as Vina cannot."),
    ],
    "Run": [
        ("The search box",
         "Most reliable when centered on the co-crystallized ligand: it marks the real site. The protein's "
         "geometric center or a cofactor point elsewhere.\n\n"
         "The X, Y and Z axes are drawn in the viewer to show which direction each control moves."),
        ("Detected cavities",
         "`Cavity` is the pocket's real extent; `Box` is the search region assigned to it, with a "
         "**14 Å minimum** because below that a ligand would not fit. When that minimum applies it is "
         "marked with `*`, so cavities of different volume can share the same box size.\n\n"
         "**Druggability** estimates whether the pocket has suitable shape and chemistry to bind a small "
         "molecule. `Flexibility` is not shown because it derives from the B-factors, which preparation "
         "sets to zero."),
        ("Hybrid docking",
         "Docks the same compounds into **several pockets** of the same receptor, each with its own "
         "ranking.\n\n"
         "It answers whether a compound prefers the catalytic site or slips into an allosteric one: "
         "**site-selectivity** information that a single-site screen does not give.\n\n"
         "Each site uses its own reference: the control if it is there, a cofactor if it falls inside the "
         "box, or the catalytic residues you designate."),
        ("Docking parameters",
         "**Exhaustiveness** — how much the search explores. Higher is finer and slower.\n\n"
         "**Poses per ligand** — how many binding modes are kept. Below 3 the confidence metric loses "
         "resolution.\n\n"
         "**Energy range** — window relative to the best pose for reporting alternative modes. It does not "
         "change the best pose or the search depth.\n\n"
         "**Seed and one thread** — guarantee that two identical runs give the same result. With more than "
         "one thread per docking, Vina stops being deterministic."),
        ("Second scoring with gnina",
         "Re-evaluates with a **neural network** the poses Vina already generated, without repeating the "
         "search.\n\n"
         "Its value is not speed but independence: Vina's score is empirical (physical terms fitted to "
         "experimental data) and gnina's is learned from crystallographic complexes. That two methods "
         "with different assumptions agree is evidence neither gives alone, and that agreement enters the "
         "confidence metric.\n\n"
         "**Limitation**: the network can only judge the poses Vina found. If the sampling missed the "
         "correct pose, re-scoring does not recover it."),
    ],
    "Results": [
        ("Effectiveness",
         "Percentage relative to that site's reference ligand, which sits at 100 %.\n\n"
         "Interaction quality does **not** measure similarity to the control: it sums each contact "
         "weighted by its bond type (salt bridge > H-bond > π > hydrophobic) and by the residue role "
         "(catalytic, secondary, cavity or external). So a compound beats the control by making **more and "
         "better productive contacts**, not by copying it."),
        ("Confidence: what it is and why it differs",
         "It is **orthogonal to effectiveness**: it measures not how good the compound is, but how much to "
         "trust the number.\n\n"
         "It is computed as a **geometric** mean —one failing piece of evidence pulls it down— of:\n\n"
         "- **conv**: binding-mode convergence, the interaction overlap between the best poses.\n"
         "- **conc**: agreement between affinity and interaction.\n"
         "- **consensus**: agreement between Vina and the neural network, if re-scoring was enabled.\n\n"
         "It drops if the target fails its redocking. **A compound with high effectiveness and low "
         "confidence is an alarm**: good score, but evidence that does not agree.\n\n"
         "`geom` (geometric spread of the poses) is shown as a diagnostic but does not enter the "
         "calculation: with Vina it is almost constant and does not discriminate."),
        ("The affinity metrics",
         "**best_dock** — Vina energy in kcal/mol; more negative is better.\n\n"
         "**pKi** — −log₁₀ of the estimated Ki. It is numeric and sortable, unlike the Ki column, which is "
         "text with mixed units. Ki **does not enter the score**: it derives from the docking score, and "
         "scoring it would count the same thing twice.\n\n"
         "**LE** (−ΔG/heavy atoms) and **LLE** (pKi−LogP) reward binding **per atom**. They guard against "
         "size bias: without them, the largest molecule almost always wins."),
        ("Catalytic and secondary residues",
         "**Catalytic** — mandatory: not touching them penalizes via the catalytic gate. They are a "
         "property of the enzyme, determined experimentally, not of the ligand.\n\n"
         "**Secondary** — known pocket anchors that add more than an ordinary contact, but are not "
         "required.\n\n"
         "If you do not know the catalytic site, PoliScreen suggests the residues with which the "
         "crystallographic ligand makes directional interactions. It is a starting point, not an answer: "
         "**this list influences the ranking more than any weight**."),
        ("Weighting",
         "The axis weights **auto-normalize**: they need not sum to 1, and setting them all to 1.0 is a "
         "simple average. If you set them all to 0 there is no score and the app warns you.\n\n"
         "An axis with weight but **no data** (toxicity without ADMET predicted) is ignored, and that is "
         "also flagged: so the Methods section does not declare something that did not intervene."),
        ("The pose column",
         "It indicates which model **all** the values in that row come from. Docking, interactions and Ki "
         "come from the same pose, never from different models."),
        ("Percentile vs. percentage",
         "The **percentage** is measured against that target's control, so it depends on how strong that "
         "control is: it is not comparable across targets.\n\n"
         "The **percentile** places the compound within its own library and does allow comparison."),
    ],
    "Reproducibility": [
        ("What is fixed",
         "Constant seed and one thread per docking; pinned environment and AutoDock Vina binary, verified "
         "by its SHA256 sum.\n\n"
         "Two runs with the same configuration give the same result."),
        ("Export the methods",
         "**File › Export Methods** generates a document with the parameters, the box, the weights, the "
         "reference used and the exact version of each tool, ready for a paper's Methods section."),
        ("Declared limitations",
         "**Rigid** docking: the receptor does not change conformation.\n\n"
         "**Non-covalent**: covalent bonds with the target are not modeled.\n\n"
         "**Estimated Ki** from Vina's affinity, which is an approximation of ΔG: it is informative, not "
         "measured.\n\n"
         "**LD50 and toxicity** come from a single predictive model and tend to be optimistic. Contrast "
         "them with a second predictor before claiming low toxicity."),
    ],
}
